<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\CPanel;

/** @var \Zend\Form\Form $form */
$form = $this->form;
$form->prepare();
?>

<div class="panel panel-flat">

    <div class="panel-body">

        <?= $this->form()->openTag($form->setAttributes([
            'class' => 'form-horizontal',
            'role' => 'form'
        ])); ?>

        <?= $this->partial('partial/element.phtml', [
            'element' => $form->get('firstname')
                ->setAttributes([
                    'required' => 'required',
                    'placeholder' => $this->translate('Enter user first name')
                ]),
            'label' => $this->translate('First Name'),
        ]); ?>

        <?= $this->partial('partial/element.phtml', [
            'element' => $form->get('lastname')
                ->setAttributes([
                    'required' => 'required',
                    'placeholder' => $this->translate('Enter user last name')
                ]),
            'label' => $this->translate('Last Name')
        ]); ?>

        <?= $this->partial('partial/element.phtml', [
            'element' => $form->get('username')
                ->setAttributes([
                    'required' => 'required',
                    'placeholder' => $this->translate('Enter username')
                ]),
            'label' => $this->translate('Username')
        ]); ?>

        <?= $this->partial('partial/element.phtml', [
            'element' => $form->get('email')
                ->setAttributes([
                    'required' => 'required',
                    'placeholder' => $this->translate('Enter user email'),
                    'autocomplete' => 'off'
                ]),
            'label' => $this->translate('Email')
        ]); ?>

        <?= $this->partial('partial/element.phtml', [
            'element' => $form->get('password')
                ->setAttributes([
                    'placeholder' => $this->translate('Enter user password'),
                    'autocomplete' => 'off'
                ]),
            'label' => $this->translate('Password')
        ]); ?>

        <?= $this->partial('partial/element.phtml', [
            'element' => $form->get('confirm')
                ->setAttributes([
                    'placeholder' => $this->translate('Confirm user password'),
                    'autocomplete' => 'off'
                ]),
            'label' => $this->translate('Confirm')
        ]); ?>

        <div class="text-right">
            <button type="reset" class="btn btn-default">Reset</button>
            <button type="submit" class="btn btn-primary">
                Submit
                <i class="icon-arrow-right14 position-right"></i>
            </button>
        </div>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>